version: '3.8'
services:
  zabbix-proxy:
    image: zabbix/zabbix-proxy-sqlite3:ol-7.0.16
    user: 
    environment:
      - ZBX_SERVER_HOST=
      - ZBX_HOSTNAME=
      - ZBX_SERVER_PORT=10051
      - ZBX_LOGTYPE=file
      - ZBX_LOGFILE=/var/log/zabbix/zabbix_proxy.log
      - ZBX_LOGFILESIZE=0
      - ZBX_ENABLEREMOTECOMMANDS=1
      - ZBX_PROXYOFFLINEBUFFER=24
      - ZBX_PROXYBUFFERMODE=hybrid
      - ZBX_PROXYMEMORYBUFFERSIZE=64M
      - ZBX_PROXYMEMORYBUFFERAGE=600
      - ZBX_PROXYCONFIGFREQUENCY=300
      - ZBX_STARTVMWARECOLLECTORS=1
      - ZBX_VMWARECACHESIZE=16M
      - ZBX_ENABLE_SNMP_TRAPS=false
      - ZBX_CACHESIZE=32M
      - ZBX_HISTORYCACHESIZE=32M
      - ZBX_TIMEOUT=30
      - ZBX_LOGSLOWQUERIES=3000
      - ZBX_ALLOWROOT=0
      - ZBX_TLSCONNECT=psk
      - ZBX_TLSACCEPT=psk
      - ZBX_TLSPSKIDENTITY=
      - ZBX_TLSPSKFILE=
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home
      - zabbix-proxy-logs:/var/log/zabbix
      - zabbix-proxy-data:/var/lib/zabbix
    networks:
      - host
networks:
  host:
    name: host
    external: true
volumes:
  zabbix-proxy-data:
  zabbix-proxy-logs:
